### PR TITLE
prevent nuke books

### LINKED ISSUE #15: Enchants aren't stripped from books
In servers with a creative world this can allow players to bring hacked books with impossible enchants into the server.
By getting a written book with enchants (for example, looting 255) in a creative world, you can /post this to yourself (or others) and quickly go to the survival world to get it. 

This can be remedied by denying /post permissions in creative worlds/gamemodes if the permission plugin has this functionality, but I'm of the opinion that the plugin could deal with this too.

I think the ideal solution here is to have a permission that strips the enchants of the book if it isn't set. This can be done with https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#hasEnchants() and https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#removeEnchant(org.bukkit.enchantments.Enchantment)

### PR DESCRIPTION
**Pull request by maeeeeee**
because of course someone decided to do this

probably fixes #15 but if I'm being completely honest this was done in like 5 minutes and I didn't check shit other than this

### CODE REVIEW

**Comment by jeremynoesen** [comment]
The code is what I would do, but the commit is a little funky (author, message). I will implement this in the next couple weeks during my winter break. or merge this PR and fix the commit idk.

**Comment by maeeeeee** [comment]
ok but what if I unfuck the PR

first time using github btw

**Comment by jeremynoesen** [comment]
perhaps 👀

**Comment by maeeeeee** [comment]
this is the stupidest shit ever

**Pull request closed without merging**
